application.name: virtual-threa-mvc-server

server:
  shutdown: graceful
  port: 20001
  tomcat:
    accept-count: 100000
    max-connections: 10000

spring:
  threads:
    virtual:
      enabled: false
  main:
    web-application-type: servlet
  flyway:
    enabled: true
    # 마이그레이션 스크립트 위치 (기본값과 동일하지만 명시)
    locations: classpath:db/migration
    # JDBC로 접속할 DB 정보 (R2DBC 아님!)
    url: jdbc:mysql://localhost:3306/virtual-thread-vs-webflux-benchmark?useUnicode=true&characterEncoding=utf8&connectionTimeZone=UTC
    user: myuser
    password: secret
    # 선택 항목들
    baseline-on-migrate: false
    clean-disabled: false
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/virtual-thread-vs-webflux-benchmark?useUnicode=true&characterEncoding=utf8&connectionTimeZone=UTC
#    username: myuser
#    password: secret
    hikari:
      pool-name: Hikari-VT
      maximum-pool-size: 64    # ✨ 동일 N (DB 병목 동일화)
      minimum-idle: 64
#      connection-timeout: 5000
#      validation-timeout: 1000
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/virtual-thread-vs-webflux-benchmark?useUnicode=true&characterEncoding=utf8&connectionTimeZone=UTC
      username: myuser
      password: secret
      max-lifetime: 540000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true      # 보기 좋게 정렬(선택)
        highlight_sql: true   # 색상 하이라이트(선택)
        jdbc:
          batch_size: 50
          time_zone: UTC
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      client-id: "YOSEP-MVC-SERVER"
      retries: 3
      batch-size: 100
      compression-type: gzip
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: 1
      properties:
        linger.ms: 50
    consumer:
      group-id: "YOSEP-MVC-SERVER"
      enable-auto-commit: false
      max-poll-records: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: '*'
    listener:
      concurrency: 1
      ack-mode: manual_immediate
      poll-timeout: 3000
      type: single
  data:
    redis:
      host: localhost
      port: 6379

kafka:
  topic:
    test:
      test-1: yosep-mvc-server-test-1

webclient:
  external:
    connection-timeout: 60000
    response-timeout: 60000
    read-timeout: 60000
    write-timeout: 60000
    byte-cnt: 2097152  # 2 * 1024 * 1024
